### ISSUE TITLE
The same AVxxx shouldn't be used for multiple purposes.

### ISSUE THREAD

**Issue by rwv37** [bkoelman/CSharpGuidelinesAnalyzer#125]
Often, in practice, reuse of the same AVxxx for related things isn't problematic, but in some cases it is. I think it would be better just to always have one purpose per AVxxx, so as not to run into such issues in certain (perhaps unforeseen) circumstances.

The example that I've currently run up against is AV2210, which (as of recently) can mean either "treat warnings as errors" or "use the highest warning level". One of the first things I've always done previously when using this analyzer on a new project is to turn off AV2210, because I absolutely do not want to treat warnings as errors. However, I _would_ like to be warned if my project is not using the highest warning level. Unfortunately, unless I'm misunderstanding something, due to the fact that both of these different things use the same AVxxx, I cannot turn one off while leaving the other on.

**Comment by rwv37** [comment]
> So my question is then: aside from AV2210, what rules would you like to see split and into which parts exactly?

I'm sorry, I don't remember - I hadn't used CSharp Guidelines Analyzer for quite some time (years, maybe?), and only recently started again. I definitely do remember having this same sort of problem with it in the past (for things other than AV2210, which this problem wasn't present for back when I had been using it). I will try to keep this in mind as I use it more, and if I notice any others, I will mention them.

**Comment by bkoelman** [comment]
@rwv37 I've removed the check on warning level from AV2210, because since .NET 5 this cannot be reliably verified anymore from an analyzer out-of-the-box (see https://github.com/bkoelman/CSharpGuidelinesAnalyzer/commit/90174eafccf08514c856a1a0a1fa6adcfc15521a for details).

I'm closing this, but if you find other cases where you'd like to be able to tweak behavior using configuration or split-up rules, please feel free to open a new issue.

**Comment by rwv37** [comment]
@bkoelman  Thank you!
