### ISSUE TITLE
 Add records as an exception to AV1564 (avoid signatures that take a bool parameter)

### ISSUE THREAD

**Issue by weelink** [bkoelman/CSharpGuidelinesAnalyzer#143]
#### Analyzer

AvoidBooleanParameterAnalyzer

#### Repro steps

```csharp
public record CustomerImportedEvent(Guid Id, string Name, bool PlatinumLevel);
```

#### Expected behavior

No warning, In the `public Customer CreateCustomer(bool platinumLevel)` example, it matters because
it indicates the method is probably doing more than one thing. But this is pure data, so there is no behaviour at all.

#### Actual behavior

Parameter 'PlatinumLevel' is of type 'bool'

**Comment by bkoelman** [comment]
Hi @weelink, thanks for bringing this up. You're proposing a change in the analyzer, but it looks like what you really want is to change the rule itself.

The rule mentions the following:
> Consider the following method signature:
> ```c#
> public Customer CreateCustomer(bool platinumLevel)
> {
> }
> ```
> On first sight this signature seems perfectly fine, but when calling this method you will lose this purpose completely:
> ```c#
> Customer customer = CreateCustomer(true);
> ```

As far as I'm aware, the analyzer implementation just follows the rule definition (a _signature_ that takes a bool parameter). It never had an exception for constructor parameters, so that's why you're seeing this behavior. Replacing the boolean with an enumeration fixes the problem of making it hard to see what the boolean represents at the call site. Because the same problem exists when using constructors, I don't think the analyzer should be changed, unless the rule itself changes. But I don't see why it should. Because it has the same problem:
```c#
var event = new CustomerImportedEvent(Guid.NewGuid(), "some", true); // what does 'true' mean here?
```

There are exceptions in the analyzer, such as being silent when the dispose pattern is implemented `(protected virtual void Dispose(bool disposing)`) or the signature is overridden from a base type or interface. Those cases cannot be fixed by a developer, so it makes sense to keep silent. I don't think your proposal falls in that category.
