### ISSUE TITLE
Suggestion: Allow short names for lambda variables (AV1706)

### ISSUE THREAD

**Issue by dennisdoomen** [bkoelman/CSharpGuidelinesAnalyzer#147]
#### Analyzer

AV1706 : Parameter 'p' should have a more descriptive name

Example: AssignVariablesInSeparateStatementsAnalyzer

#### Repro steps

Consider the following statement:

```csharp            
var description = apiDescription.ParameterDescriptions.First(p => p.Name == parameter.Name);
```

I think that in this context `p` is clear enough. Trying to come up with a different name might result in ugly alternatives.

**Comment by bkoelman** [comment]
Well, the rule is pretty clear:
> Avoid single character variable names, such as i or q. Use index or query instead.

Why not just use "description" or "nextDescription"?

**Comment by bkoelman** [comment]
> I think that in this context p is clear enough. Trying to come up with a different name might result in ugly alternatives.

The same could be said about the next line:
```c#
for (int i = 0; i < count; i++)
```
But then someone adds a nested loop later and chooses `j`...

Likewise, building the startup host may cause deep nestings, such as:
```c#
builder.services
    .AddHttpClient(...)
        .AddMessageHandler(b => b.Services.GetRequiredService...
```

In the above, it's not at all obvious that `b` is an `IHttpClientBuilder`, so replacing that with `httpClientBuilder` or `clientBuilder` makes it easier to understand.

Sometimes I see people use `x` for every lambda parameter. And getting into trouble when nested.

In other cases I've seen `b` for `IConfiguration` lambda parameters, pretty misleading. Resharper doesn't auto-rename `b` when the source type changes, but it does when the names are similar. 

I've gotten used to never using single-char names anymore. It works pretty well for me.

**Comment by dennisdoomen** [comment]
I get your point, but I don't agree on every point. Since longer names get duplicated when using lambdas, people tend to use abbreviations like `par` instead. You know I care about good naming, applying the Roslyn analyzer (and my own guidelines) made me realize I'm totally fine with short names in lambda predicates.

I guess I need to start this discussion in the guidelines first ;-)

**Comment by bkoelman** [comment]
Abbreviations aren't allowed either. Are you suggesting to allow them?

**Comment by dennisdoomen** [comment]
Yes, just for lambdas. For example, I prefer

`var description = apiDescription.ParameterDescriptions.First(p => p.Name == parameter.Name);`

over 

`var description = apiDescription.ParameterDescriptions.First(description => description.Name == parameter.Name);`

**Comment by bkoelman** [comment]
I suppose single-char names are a form of abbreviations. Though I find "opts", "exc" and "cfg" far worse than a single character; they come across as just being lazy. Resharper triggers spelling errors on them.

Allowing single-char names raises the question whether a lambda parameter of type `IServiceProvider` can be named "sp", it's a slippery slope. And would it be okay to refer to `IAuthorizationProviderFactory` as "apf" inside a lambda? Isn't this like Hungarian notation all over again? 

Abbreviations are covered at https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/general-naming-conventions#using-abbreviations-and-acronyms. If we were to deviate from that, what would be the motivation to do so?

> Since longer names get duplicated when using lambdas, people tend to use abbreviations like par instead.

What do you mean by getting duplicated? I wonder how you would prefer to name things when multiple nested builders of different types are involved? b, bb, b2?

My point of view stems from working on a codebase where single-char and abbreviations were all over the place. For example,  code looked initially like:
```c#
var opts = sp.GetRequiredService<IOptions<EndpointOptions>>();
SetOptions(opts.Value);
```
The last method was later refactored by someone else to require `IOptionsMonitor`. So the developer changed the code to:
```c#
var opts = sp.GetRequiredService<IOptionsMonitor<EndpointOptions>>();
SetOptions(opts);
```
But he didn't bother to rename `opts` because it already looked messy before his changes. This is how codebases deteriorate.

I'm curious why you think lambda parameters should be treated differently from regular variables. What makes them different? They may be short-lived initially, but in time the code can be changed to take a large statement block instead of an expression. That looks pretty horrible with meaningless names. I've encountered quite a few of those, particularly in `ConfigureOptions`.

**Comment by bkoelman** [comment]
Related: https://stackoverflow.com/questions/443466/lambda-variable-names-to-short-name-or-not-to-short-name
